version: '3.8'
services:
  github-runner:
    image: tcardonne/github-runner:latest  # This image supports PAT
    container_name: github-runner
    environment:
      GITHUB_OWNER: "Morawski21"
      GITHUB_REPOSITORY: "personal-logs-20" 
      GITHUB_PAT: {PAT}
      RUNNER_LABELS: "linux,x64,synology,docker"
      RUNNER_NAME: "synology-runner"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-data:/home/runner
    restart: unless-stopped
    privileged: true

volumes:
  runner-data: