version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - EXCEL_DATA_PATH=./data
      - CORS_ORIGINS=*
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.0.53:8000
        - NEXT_PUBLIC_WS_URL=ws://192.168.0.53:8000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.0.53:8000
      - NEXT_PUBLIC_WS_URL=ws://192.168.0.53:8000
    depends_on:
      - backend
    restart: unless-stopped